### ISSUE TITLE
Can we get a JSON list?

### ISSUE THREAD

**Issue by arijitdasgupta** [hemanth/why-babies-cry#4]
I was wondering if I can make a portal and people can click when they figure out why a baby is/was crying and would like to keep the numbers in buckets.

And the deployment can pull from this git repo.

I just didn't want to write a parser to parse a text file to get all the reasons. :-P

**Comment by arijitdasgupta** [comment]
Or nevermind, I will write a parser. Please make sure the list stays this way.

**Comment by hemanth** [comment]
![3oz8xvdYbeMUmxGfjG](https://camo.githubusercontent.com/2a611e2fb69903e861c298d0b38b6cf85d75f9fb/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f336f7a387876645962654d556d7847666a472f67697068792e676966)
